# T-Pot (Standard)
# Do not erase ports sections, these are used by /opt/tpot/bin/rules.sh to setup iptables ACCEPT rules for NFQ (honeytrap / glutton)
version: '2.3'

networks:
  etc_local:
  # adbhoney_local:
  # citrixhoneypot_local:
  # conpot_local_IEC104:
  # conpot_local_guardian_ast:
  # conpot_local_ipmi:
  # conpot_local_kamstrup_382:
  # cowrie_local:
  
  # dicompot_local:
  # dionaea_local:
  # elasticpot_local:
  # heralding_local:
  # honeysap_local:
  # mailoney_local:
  # medpot_local:
  # rdpy_local:
  # tanner_local:
  # ewsposter_local:
  # spiderfoot_local:

services:


##################
#### Tools
##################



## Peba  service
  peba:
    container_name: peba
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
     - "9922:8000"
    image: "jbanana/peba:latest"


#### ELK
## Elasticsearch service
  elasticsearch:
    container_name: elasticsearch
    restart: always
    environment:
     - bootstrap.memory_lock=true
     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
     - ES_TMPDIR=/tmp
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
     - "64298:9200"
    image: "dtagdevsec/elasticsearch:2006"
    volumes:
     - /data:/data

## Kibana service
  kibana:
    container_name: kibana
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
     - "127.0.0.1:64296:5601"
    image: "dtagdevsec/kibana:2006"

## Logstash service
  logstash:
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xms2048m -Xmx2048m
    depends_on:
      elasticsearch:
        condition: service_healthy
    env_file:
     - /opt/tpot/etc/compose/elk_environment
    image: "dtagdevsec/logstash:2006"
    volumes:
     - /data:/data

## Elasticsearch-head service
  head:
    container_name: head
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
     - "127.0.0.1:64302:9100"
    image: "dtagdevsec/head:2006"
    read_only: true

# # Ewsposter service
#   ewsposter:
#     container_name: ewsposter
#     restart: always
#     networks:
#      - ewsposter_local
#     environment:
#      - EWS_HPFEEDS_ENABLE=false
#      - EWS_HPFEEDS_HOST=host
#      - EWS_HPFEEDS_PORT=port
#      - EWS_HPFEEDS_CHANNELS=channels
#      - EWS_HPFEEDS_IDENT=user
#      - EWS_HPFEEDS_SECRET=secret
#      - EWS_HPFEEDS_TLSCERT=false
#      - EWS_HPFEEDS_FORMAT=json
#     env_file:
#      - /opt/tpot/etc/compose/elk_environment
#     image: "dtagdevsec/ewsposter:2006"
#     volumes:
#      - /data:/data
#      - /data/ews/conf/ews.ip:/opt/ewsposter/ews.ip

# Nginx service
  nginx:
    container_name: nginx
    restart: always
    environment:
    ### If set to YES all changes within Heimdall will remain for the next start
    ### Make sure to uncomment the corresponding volume statements below, or the setting will prevent a successful start of T-Pot.
     - HEIMDALL_PERSIST=NO
    tmpfs:
     - /var/tmp/nginx/client_body
     - /var/tmp/nginx/proxy
     - /var/tmp/nginx/fastcgi
     - /var/tmp/nginx/uwsgi
     - /var/tmp/nginx/scgi 
     - /run
     - /var/log/php7/
     - /var/lib/nginx/tmp:uid=100,gid=82 
     - /var/lib/nginx/html/storage/logs:uid=100,gid=82
     - /var/lib/nginx/html/storage/framework/views:uid=100,gid=82
    network_mode: "host"
    ports:
     - "64297:64297"
     - "127.0.0.1:64304:64304"
    image: "dtagdevsec/nginx:2006"
    read_only: true
    volumes:
     - /data/nginx/cert/:/etc/nginx/cert/:ro
     - /data/nginx/conf/nginxpasswd:/etc/nginx/nginxpasswd:ro
     - /data/nginx/log/:/var/log/nginx/
    ### Enable the following volumes if you set HEIMDALL_PERSIST=YES
    # - /data/nginx/heimdall/database:/var/lib/nginx/html/database
    # - /data/nginx/heimdall/storage:/var/lib/nginx/html/storage

# # Spiderfoot service
#   spiderfoot:
#     container_name: spiderfoot
#     restart: always
#     networks:
#      - spiderfoot_local
#     ports:
#      - "127.0.0.1:64303:8080"
#     image: "dtagdevsec/spiderfoot:2006"
#     volumes:
#      - /data/spiderfoot/spiderfoot.db:/home/spiderfoot/spiderfoot.db
